lib/logstash/inputs/elasticsearch.rb, spec/inputs/elasticsearch_spec.rb
* refactors specs to use the input spec helper in devutils
* also slightly adapts the scan vs scroll logic to ensure scan works.
* removes the :elasticsearch tag from 2 tests, that can be run offline without elasticsearch
This requires (actually includes) #24
=> Fix specs and scan

CHANGELOG.md, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec
- few code cleanups
- reworked field assignment to not assume in-place mutability of Event inner structure
relates to elastic/logstash#4264 and elastic/logstash#4191
=> do not assume event field ref to return in-place mutable structure

lib/logstash/inputs/elasticsearch.rb
Make the expected file format and requirement for any chain certificates clearer.
Open to improvements on the wording of this doco text.
=> Update to docs for SSL ca_file option

CHANGELOG.md, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec
Adds compatibility note requested in elastic/logstash#6718
@acchen97 Here's the one for the input plugin for review.
=> Add plugin level required to support sending content-type headers

CHANGELOG.md, lib/logstash/inputs/elasticsearch.rb, spec/inputs/elasticsearch_spec.rb
This makes scrolling incompatible with ES 1.x
NOTE: It's already documented that version 5.x of elasticsearch-ruby gem isn't compatible with ES 1.x, so it should be ok to break scrolling here.
fixes https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/62
=> Fix scrolling requests by using json formatted bodies

CHANGELOG.md, docs/index.asciidoc, logstash-input-elasticsearch.gemspec
Plugin doc changes related to logstash-plugins/logstash-output-elasticsearch#691
Adds statement indicating that `document_type` is deprecated. 
I thought about removing `document_type` from the example but that begs the question: how do we deal with the `_type` as one of the default fields in the `docinfo` array? Are we going to remove the field? When we do, we can remove `document_type` from the example.
Also fixed a couple of links that were coded incorrectly.
(Note that the changes in this PR are related to https://github.com/elastic/logstash/pull/8603)
=> Deprecate `document_type` in the docs

docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb
Ported from _logstash-input-jdbc_ plugin the support for rufus based cron-like scheduling, i.e.
```
input {
elasticsearch {
hosts => [...]
query => ...
schedule => "*/10 * * * * * UTC"
}
}
```
=> Scheduling support

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, spec/inputs/elasticsearch_spec.rb
Adds a `slices` option; when given, the input will use the Sliced Scroll api to consume the query via multiple slices in parallel.
I'm not entirely sure the best way to add tests. When implemented as unit tests, I end up having to stub out a series of client calls and responses, which leads me to the point where I'm unsure whether I'm testing the code or my stubs.
=> Add managed multi-slice scrolling with `slices` option.

CHANGELOG.md, logstash-input-elasticsearch.gemspec
```
% git lg v4.2.1..
* be3ea46 - (origin/master, master) [skip ci] Travis: update LOGSTASH_BRANCH from 6.[0..4] to 6.5 (4 weeks ago) <Rob Bavey>
* 762e540 - pin bundler version to < 2 (5 weeks ago) <Rob Bavey>
* 34308c0 - Merge pull request #94 from yaauie/managed-slices-option (5 months ago) <Ry Biesemeyer>
* 939f343 - add managed slice scrolling with `slices` option. (5 months ago) <Ry Biesemeyer>
```
=> bump to 4.3.0

spec/inputs/elasticsearch_spec.rb
Remove use of Hash#except, which was previously brought in via the
'i18n' gem, but, as of 7.0 no longer appears to be the case, and is
causing test failures
=> Remove Hash#except from failing spec.

CHANGELOG.md, docs/index.asciidoc, logstash-input-elasticsearch.gemspec
The link target to sliced scrolls in the ES Ref changed. This PR corrects the link.
=> [Doc]Update link to sliced scrolls doc

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb
inspired by the ES output plugin: logstash-plugins/logstash-output-elasticsearch#906
docs all the same
=> Feat: support cloud_id / cloud_auth configuration

CHANGELOG.md, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb
Fixes #122 
- Explicitly call the ES client `clear_scroll` API after each search operation
- Handle scroll_request exceptions
=> Add robustness around scrolling

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb
This is currently based on  #128 which is pending LGTM  - I will rebase once merged.
Related to https://github.com/elastic/logstash/issues/11788
- Add support for [elasticsearch API key](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html) authentication using the `api_key` option
- SSL must be enabled
- Only one authentication method must be specified out of (`user`/`password`, `cloud_auth` and `api_key`)
=> add support for api_key authentication

.ci/docker-compose.override.yml
ELASTIC_STACK_VERSION was not being passed down to the docker image
causing the ESHelper.version_satisfies? helper method report the wrong
version, causing tests to fail due to doc types being incorrectly set.
=> Pass `ELASTIC_STACK_VERSION` env variable to docker image

docs/index.asciidoc
This PR is trying to address the issue https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/82
Documentation update to add usage example of docinfo metadata in add_field common option.
As the `add_field` is in the common options, I find it difficult to include the example of usage of the docinfo metadata in the associated section.
So I've choosen the `docinfo` section, where it was worth mentioning the metadata can be used only if `docinfo` is set.
I am totally open to change it if you have a better option.
The doc should also be applied to v4.1.0 (as this feature was added via https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/78).
=> [documentation][issue/82] Add usage example of docinfo metadata in add_field

CHANGELOG.md, docs/index.asciidoc, logstash-input-elasticsearch.gemspec
Elasticsearch doc improvements and restructuring broke a link. This work fixes it. 
Minor edits.
=> Doc:Update sliced scroll link to resolve to new location

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb
default values were chosen from the current default behaviour of these
transport options as provided by the Manticore transport adapter we provide to
the Elasticsearch Client:
> ~~~
> request_timeout (integer) — default: 60 — Sets the timeout for requests.
> connect_timeout (integer) — default: 10 — Sets the timeout for connections.
> socket_timeout (integer)  — default: 10 — Sets `SO_TIMEOUT` for open connections. A value of 0 is an infinite timeout.
> ~~~
>
> -- [Manticore::Client#initialize](https://www.rubydoc.info/gems/manticore/Manticore/Client#initialize-instance_method)
I have elected _not_ to allow an infinite `socket_timeout` by requiring
the provided value to be positive, as I can see no valid use-case of such
using Elasticsearch's HTTP API.
Resolves #121
***
Includes a minor …
=> make connection, request, and socket timeouts configurable

CHANGELOG.md, lib/logstash/inputs/elasticsearch.rb, lib/logstash/inputs/patch.rb, logstash-input-elasticsearch.gemspec
Patched the RoudRobin policy used by the underlying elasticsearch-transport gem.
In case of multiple slices there are one thread per slice and the library exposed a race condition while not protecting the access to the connections pool.
Fixes: #133
=> Fix concurrency bug that avoided to retrieve connection when using multiple slices

CHANGELOG.md, docs/index.asciidoc, logstash-input-elasticsearch.gemspec
[Cloud rework](https://github.com/elastic/logstash/pull/11884) broke some links from the plugins. This PR updates the links and points one level up in docs to give user a bit more context for logstash->cloud.
Fixes: #138
=> Doc: Update links to logstash-to-cloud docs

.ci/docker-setup.sh, CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb
Adding a `target` option to the input allows users to specifically target where `_source` of a hit will be placed instead of polluting the top-level of the event.
Combined with the existing `docinfo_fields` and `docinfo_target`, this new setting can be used to ensure that _only_ known fields are populated at the root level, making it easier to define pipelines that are consistently compatible with a schema like ECS.
=> Introduce `target` option

CHANGELOG.md, docs/index.asciidoc, logstash-input-elasticsearch.gemspec
Standardize links to other Elastic docs to use shared attributes
Bump to v.4.9.1
=> Doc: Replace cross doc links with attributes

spec/inputs/elasticsearch_spec.rb
when running against latest 8.0/7.14 snapshots some tests started failing 
due using *elasticsearch* client API that is [lacking in version 7.14.0](https://github.com/elastic/elasticsearch-ruby/blob/v7.14.0/elasticsearch-transport/lib/elasticsearch/transport/client.rb):
- `undefined method 'hosts' for #<Elasticsearch::Transport::Client:0x18a7c1f6>`
- `undefined method 'options' for #<Elasticsearch::Transport::Client:0x2eb8e649>`
resolves https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/151
=> Test: fix compat issue with latest client

CHANGELOG.md, logstash-input-elasticsearch.gemspec
the fix in upstream has merged and [released](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1032#issuecomment-900782420) in 0.7.1 gem
Hence, update manticore
Fix: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1033
Related: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1032
=> Fixed SSL handshake hang indefinitely with proxy setup

spec/inputs/elasticsearch_spec.rb
Refactoring of test code, avoiding the "old" `input(config) do |pipeline, queue| ...` format.
motivated mostly due (still - https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/169) running into:
```
logstash_1_c3816da54f91 |      Failure/Error: @client.search(options)
logstash_1_c3816da54f91 |        #<Double "elasticsearch-client"> was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one example, and you need to create a new one in each example you wish to use it for.
logstash_1_c3816da54f91 |      # ./lib/logstash/inputs/elasticsearch.rb:361:in `search_request'
logstash_1_c3816da54f91 |      # ./lib/logstash/inputs/elasticsearch.rb:290:in `do_run_slice' …
```
=> Test: less double leaking failures (on CI)

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, spec/inputs/elasticsearch_spec.rb
As per customers request, this PR intends to add an option to control SSL certificate validation.
Closes #33 
```
$rspec spec/inputs/elasticsearch_spec.rb:702
Finished in 0.63507 seconds (files took 2.33 seconds to load)
1 example, 0 failures
```
1. Use following configuration, make sure to set ES endpoint, user name and password
```
input {
elasticsearch {
index => "ssl-certificate-validation-test"
query => '{ "query": { "match": { "host.hostname": "mashhur-local" } } }'
ssl => true
ssl_certificate_verification => false
}
}
output { stdout {}}
```
2. Run Logstash and check if it is giving a `WARN` about data security risk
```
bin/logstash -f config/ssl-disabled.conf
[2022-08-10T09:35:08,662][WARN ][logstash.inputs.elasticsearch][main] You have enabled encryption but DISABLED certificate …
```
=> An option to control SSL certificate validation added.

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb, spec/inputs/elasticsearch_ssl_spec.rb, spec/inputs/integration/elasticsearch_spec.rb
Added the following SSL settings:
`ssl_enabled`: Enable/disable the SSL settings. Infer the value from the hosts' scheme if neither the deprecate :ssl nor the new :ssl_enabled configs were set
`ssl_certificate`: OpenSSL-style X.509 certificate file to authenticate the client
`ssl_key`: OpenSSL-style RSA private key that corresponds to the `ssl_certificate`
`ssl_truststore_path`: he JKS truststore to validate the server's certificate
`ssl_truststore_type`: The format of the truststore file
`ssl_truststore_password`: The truststore password
`ssl_keystore_path`: The keystore used to present a certificate to the server
`ssl_keystore_type`: The format of the keystore file
`ssl_keystore_password`: The keystore password
`ssl_cipher_suites`: The list of cipher suites to use …
=> Standardize and add SSL settings

CHANGELOG.md, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb, spec/inputs/elasticsearch_ssl_spec.rb
This commit adds "Elastic-Api-Version" : "2023-10-31" to request header when the Elasticsearch is serverless
=> Add Elastic Api Version header

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, lib/logstash/inputs/elasticsearch/paginated_search.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb, spec/inputs/integration/elasticsearch_spec.rb, spec/inputs/paginated_search_spec.rb
This commit introduces the `search_api` option to enable support for both `search_after` and `scroll`. 
| `search_api`  | description  |
|-----------|-----------|
| `auto`    | Default value. It uses `search_after` for Elasticsearch 8 and newer versions, otherwise, it falls back to the `scroll` API    |
| `search_after`    | Create a point in time for search, which is the recommended way to do paginated search since 7.10   |
| `scroll`   | Uses scroll API to search, which is the previous way to search    |
When `search_after` is utilized, if the query doesn't specify a sort field, a default sort of `{ "sort": { "_shard_doc": "asc" } }` will be added to the query. By default, Elasticsearch adds a sort field "_shard_doc" on top of existing sort implicitly as a tie-breakers.
The scroll …
=> Add support to search after

CHANGELOG.md, logstash-input-elasticsearch.gemspec
Some doc formatting errors don't require version bumps, and can wait until the next time we need to bump versions.  Turns out that the fix in #199 does require a version bump to get us past CI failures.  I can't fix the error in output (as I did for the VPR) until we successfully generate output.
=> Bump to v4.19.1 to pick up doc fix needed for docgen

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, lib/logstash/inputs/elasticsearch/aggregation.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb
Add `response_type` configuration option to allow processing result of aggregations.
The default `hits` will generate one event per returned document (i.e. "hit"), which is the current behavior.
When set to `aggregations`, a single Logstash event will be generated with the contents of the `aggregations` object of the query's response. In this case the `hits` object will be ignored.
The parameter `size` will be always be set to 0 regardless of the default or user-defined value set in this plugin.
builds upon and replaces #197 
closes #58
=> Support aggregations

CHANGELOG.md, docs/index.asciidoc, logstash-input-elasticsearch.gemspec
The "Multi-target syntax" link resolves to a [redirect page](https://www.elastic.co/guide/en/elasticsearch/reference/master/multi-index.html), requiring users to make another click to get to the [content](https://www.elastic.co/guide/en/elasticsearch/reference/master/api-conventions.html#api-multi-index). Yikes! 
This PR updates the link to resolve to the correct content.
=> Doc: Update link to resolve to target content

.travis.yml
If we don't include the `env` matrix row in the stage definition entry, then the previous entry is put under the next stage.
We can see this where a non integration test shows up in the integration test stage:
Build: https://app.travis-ci.com/github/logstash-plugins/logstash-input-elasticsearch/builds/273186251
Image:
=> Update .travis.yml to properly separate testing stages

CHANGELOG.md, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb
This commit updates the `Elasticsearch::Client` used to make requests to ES to send along a header identifying the request as originating from an internal component.
Closes https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/212
=> Set x-elastic-product-origin header for ES requests

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec, spec/inputs/elasticsearch_spec.rb
Get rid of the deprecated parameters and document their removal. Ensure the integration and unit tests pass and that the removals are clearly documented. 
Closes https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/210
=> Remove deprecated SSL settings and simplify SSL configuration

docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, spec/inputs/elasticsearch_spec.rb
This adds support for custom headers to be specified in the input configuration and included in transport options. 
custom_headers => {"Header Name" => "Value"}
=> Adding support for custom headers

CHANGELOG.md, lib/logstash/inputs/elasticsearch.rb, logstash-input-elasticsearch.gemspec
Adds elastic-transport client support where opens LS-core a way to start using newer ES ruby client.
FYI: failed [Test plugin docs](https://github.com/logstash-plugins/logstash-input-elasticsearch/actions/runs/13647730753?pr=223) CI is not related to this change.
=> Adds elastic-transport client support

spec/inputs/elasticsearch_spec.rb
Fixes the unit test failures caused by #223.
The failures became visible once LS-core upgraded elasticsearch-ruby client to 8.x.
=> Fix the unit test failures caused by #223

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, lib/logstash/inputs/elasticsearch/aggregation.rb, lib/logstash/inputs/elasticsearch/cursor_tracker.rb, lib/logstash/inputs/elasticsearch/paginated_search.rb, logstash-input-elasticsearch.gemspec, spec/inputs/cursor_tracker_spec.rb, spec/inputs/elasticsearch_spec.rb, spec/inputs/integration/elasticsearch_spec.rb
With this change it's possible to configure a "tracking_field" whose value is injected into the query using the `:last_value` keyword, and a `:present` field that represents `now - 30s`.
Example configuration:
```
input {
elasticsearch {
id => tail
hosts => [ 'https://host...']
api_key => "..."
index => "my_data"
query => '{ "query": { "range": { "event.ingested": { "gt": ":last_value", "lt": ":present"}}}, "sort": [ { "event.ingested": {"order": "asc", "format": "strict_date_optional_time_nanos", "numeric_type" : "date_nanos" } } ] }'
tracking_field => "[event][ingested]"
tracking_field_seed => "1980-01-01T23:59:59.999999999Z"
slices => 5
schedule => '* * * * *'
schedule_overlap => false
}
}
output {
elasticsearch { .. }
}
```
To test this, follow the guidance on the doc changes from …
=> Introduce cursor tracking akin to jdbc input

CHANGELOG.md, docs/index.asciidoc, lib/logstash/inputs/elasticsearch.rb, lib/logstash/inputs/elasticsearch/aggregation.rb, lib/logstash/inputs/elasticsearch/cursor_tracker.rb, lib/logstash/inputs/elasticsearch/paginated_search.rb, logstash-input-elasticsearch.gemspec, spec/inputs/cursor_tracker_spec.rb, spec/inputs/elasticsearch_spec.rb, spec/inputs/integration/elasticsearch_spec.rb
Provide field value tracking, persisted to disk on each search_after page.
Adds `:last_value` and `:present` placeholders, allowing the plugin to inject the cursor value and now-30 seconds, respectively, in the query string.
Useful to track new data being written to an index or series of indices.
Works best with nano second precision timestamps added by Elasticsearch's Ingest Pipelines.
backport #205 to 4.x
=> Introduce cursor tracking akin to jdbc input (#205)
